<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CompanyProfile extends Model
{
    use HasFactory;

    protected $fillable = [
        'company_name',
        'description',
        'address',
        'phone',
        'email',
        'website',
        'about_us',
        'services',
        'logo',
        'hero_image',
        'hero_title',
        'hero_description',
        'hero_images',
        'hero_slides',
        'social_media',
        'footer_services_title',
        'footer_services_items',
        'footer_copyright_text',
        'footer_company_name',
        'footer_company_description',
        'footer_contact_title',
        'footer_contact_address',
        'footer_contact_phone',
        'footer_contact_email',
        'about_hero_title',
        'about_hero_subtitle',
        'about_main_text',
        'about_stat_cities',
        'about_stat_experience',
        'about_stat_projects',
        'about_feature_1',
        'about_feature_2',
        'about_feature_3',
        'about_service_1_title',
        'about_service_1_description',
        'about_service_2_title',
        'about_service_2_description',
        'about_service_3_title',
        'about_service_3_description',
        'about_service_4_title',
        'about_service_4_description',
        'about_vision_title',
        'about_vision_text',
        'about_mission_title',
        'about_mission_text',
        'home_highlight_kicker',
        'home_highlight_title',
        'home_highlight_1_label',
        'home_highlight_1_title',
        'home_highlight_1_text',
        'home_highlight_2_label',
        'home_highlight_2_title',
        'home_highlight_2_text',
        'home_highlight_3_label',
        'home_highlight_3_title',
        'home_highlight_3_text',
        'home_services_heading_title',
        'home_services_heading_subtitle',
        'home_services_1_title',
        'home_services_2_title',
        'home_services_3_title',
        'home_services_4_title',
        'home_features_heading_title',
        'home_features_heading_subtitle',
        'home_features_1_title',
        'home_features_2_title',
        'home_features_3_title',
        'home_features_4_title',
        'home_features_5_title',
        'home_features_6_title',
        'home_articles_heading_title',
        'home_articles_heading_subtitle',
        'home_projects_heading_title',
        'home_cta_title',
        'home_cta_subtitle',
        'home_cta_button_text',
        'service_sales_content',
        'service_rental_content',
        'service_delivery_content',
        'service_consultation_content'
        ,
        'service_sales_hero_title',
        'service_sales_hero_subtitle',
        'service_sales_intro_title',
        'service_sales_intro_text',
        'service_sales_section_title',
        'service_sales_section_bullets',
        'service_sales_extra_title',
        'service_sales_extra_1_title',
        'service_sales_extra_1_text',
        'service_sales_extra_2_title',
        'service_sales_extra_2_text',
        'service_sales_side_title',
        'service_sales_side_text',
        'service_sales_side_button_text',
        'service_sales_side_footer_text',
        'service_rental_hero_title',
        'service_rental_hero_subtitle',
        'service_rental_intro_title',
        'service_rental_intro_text',
        'service_rental_section_title',
        'service_rental_section_bullets',
        'service_rental_extra_title',
        'service_rental_extra_1_title',
        'service_rental_extra_1_text',
        'service_rental_extra_2_title',
        'service_rental_extra_2_text',
        'service_rental_side_title',
        'service_rental_side_text',
        'service_rental_side_button_text',
        'service_rental_side_footer_text',
        'service_delivery_hero_title',
        'service_delivery_hero_subtitle',
        'service_delivery_intro_title',
        'service_delivery_intro_text',
        'service_delivery_section_title',
        'service_delivery_section_bullets',
        'service_delivery_extra_title',
        'service_delivery_extra_1_title',
        'service_delivery_extra_1_text',
        'service_delivery_extra_2_title',
        'service_delivery_extra_2_text',
        'service_delivery_side_title',
        'service_delivery_side_text',
        'service_delivery_side_button_text',
        'service_delivery_side_footer_text',
        'service_consultation_hero_title',
        'service_consultation_hero_subtitle',
        'service_consultation_intro_title',
        'service_consultation_intro_text',
        'service_consultation_section_title',
        'service_consultation_section_bullets',
        'service_consultation_extra_title',
        'service_consultation_extra_1_title',
        'service_consultation_extra_1_text',
        'service_consultation_extra_2_title',
        'service_consultation_extra_2_text',
        'service_consultation_side_title',
        'service_consultation_side_text',
        'service_consultation_side_button_text',
        'service_consultation_side_footer_text'
    ];

    protected $casts = [
        'social_media' => 'array',
        'hero_images' => 'array',
        'hero_slides' => 'array',
        'footer_services_items' => 'array',
    ];
}
